const A=(id,type,name,desc,need,contexts,l1,l2,l3,noBall=null)=>({id,type,name,desc,need,contexts,levels:[l1,l2,l3],noBall});
const N=(need,l1,l2,l3)=>({need,levels:[l1,l2,l3]});
export const TIP9_PRACTICES=[
A('SW01','SWING','Contact','Predictable ball-first strike','Mid-iron · optional towel',['range','bay'],['Place a towel one clubhead behind the ball. Make one slow rehearsal that brushes turf ahead of the towel, then hit.','Ball first; towel untouched.'],['Remove the towel but picture it still there. Change target each ball and keep the same strike intention.','Solid contact while target changes.'],['Change club and target after every ball. Use your normal routine with no drill rehearsal.','Playable contact from a fresh start.']),
A('SW02','SWING','Tempo','Repeatable unhurried rhythm','Mid-iron',['range','bay','noball'],['Before each ball make one smooth rehearsal at about 70% effort. Feel the backswing finish before starting down, then hit at the same pace.','Balanced finish; no rush from the top.'],['Use short, mid and longer clubs. Keep the same overall rhythm with each.','Club changes; rhythm does not.'],['Randomize club and target. Step away between balls and use a full routine.','Tempo survives a one-ball environment.'],N('Golf club · safe rehearsal space',['Make three slow rehearsal swings at about 60–70% speed. Let the backswing finish before you start down, then flow through to a balanced finish.','Each rep feels unhurried; no rush from the top.'],['Reset your feet before every rep and make three rehearsals at a normal comfortable pace.','The same rhythm returns from a fresh setup.'],['Picture three real targets. Use your routine and make one committed rehearsal to each.','Target changes; tempo stays the same.'])),
A('SW03','SWING','Low Point','Move turf contact target-side of ball','Mid-iron · ground line',['range','bay'],['Draw or imagine a line. Put the ball just ahead of it. Rehearse brushing turf after the line, then hit.','Ball first, then turf.'],['Use three different irons with normal ball positions. Keep attention on where the club meets the ground.','Low point stays forward across clubs.'],['Randomize club and target. No ground rehearsal before the final three.','Ball-first strike while playing a shot.']),
A('SW04','SWING','Start Direction','Make starting window predictable','Mid-iron · two range landmarks',['range','bay'],['Choose two landmarks that make a wide start window. Hit three balls and judge only where each begins.','Ball starts inside the window.'],['Narrow the window and change target each ball. Call the start window before stepping in.','Start matches the called window.'],['Randomize club and target. Use full routine and call the intended start before every ball.','Intentional start direction under change.']),
A('SW05','SWING','Balance & Finish','Finish athletic and under control','Any iron',['range','bay','noball'],['Swing at about 70% and hold the finish for a slow count of three after every shot.','No step, stumble or fall away.'],['Return to normal comfortable speed and change club each ball while keeping the held finish.','Balance survives more speed and club length.'],['Play three imagined approach shots. Check balance only after the ball is gone.','Controlled finish without thinking about it during the swing.'],N('Golf club optional · safe rehearsal space',['Make three slow golf swings without a ball at about 60–70% effort. Hold each finish for a slow count of three.','Finish stable without stepping or falling away.'],['Reset before each rep and move at a normal comfortable pace. Hold the finish.','More speed; same control.'],['Picture three targets and make one committed rehearsal to each.','Balance shows up while attention is on the shot.'])),
A('SW06','SWING','Face Awareness','Develop simple awareness of clubface delivery','Short or mid-iron',['range','bay'],['Hit three waist-to-waist shots and watch only where each ball starts.','Start direction is reasonably repeatable.'],['Add swing length and choose left, center and right start windows.','Ball begins near the window you called.'],['Randomize target and club. Call the start, then make a normal golf swing.','Predictable starts without technical checking.']),
A('SW07','SWING','Centered Turn','Turn without excessive sway','Mid-iron',['range','bay','noball'],['Make a slow rehearsal, then hit at 70%. Feel pressure stay under you while the chest turns.','Finish centered and balanced.'],['Use normal stance and change target each ball while keeping the same centered-turn feel.','Turn remains controlled as attention moves outward.'],['Full routine, random target and club. No rehearsal on the final three.','Centered motion in a normal golf shot.'],N('Golf club optional · mirror helpful',['Make three slow backswing-and-through rehearsals. Feel your chest turn while pressure stays under your feet.','Turn without a large side-to-side sway.'],['Reset stance before each rep and repeat the centered turn at a comfortable pace.','Your center stays controlled from a fresh setup.'],['Picture three targets and make one full rehearsal to each.','Centered turn survives target intent.'])),
A('SW08','SWING','Transition','Start down without rushing','Mid-iron',['range','bay','noball'],['Pause briefly at the top of one rehearsal before each ball. Then hit smoothly without an actual pause.','Downswing starts without a lunge or rush.'],['Remove the rehearsal for one ball and bring it back only if needed. Change target each ball.','Transition remains smooth with less support.'],['Three one-ball shots to different targets with full routine.','Smooth transition under normal intent.'],N('Golf club · safe rehearsal space',['Make three slow rehearsals with a clear pause at the top. Feel the backswing finish before the downswing begins.','Change of direction feels organized, not rushed.'],['Make three more without an actual pause, keeping the same sense of finishing the backswing first.','Smooth transition without forcing a pause.'],['Picture three targets and make one normal-routine rehearsal to each.','Transition stays smooth when the motion becomes natural.'])),
A('SK01','SKILL','Start Line','Start putts where intended','Putter · straight 5–6 ft putt · optional gate',['green'],['Set a gate just wider than the ball 12–18 inches ahead. Roll three putts through it.','Ball passes through the gate.'],['Use three different 5–7 ft putts. Pick a start point before each stroke.','Ball starts over the chosen point.'],['Move after every putt. Read, commit and roll one ball only.','Committed start line on first attempt.']),
A('SK02','SKILL','Lag Putting','Leave long putts close','Putter · 20/30/40 ft space',['green'],['Hit one putt from roughly 20, 30 and 40 feet to one hole.','Finish inside 3 feet.'],['Randomize the three distances and use different slopes.','Finish inside 3 feet without repeating a putt.'],['Play three new long putts as if on course; no second attempts.','Every next putt is comfortable.']),
A('SK03','SKILL','Short Putting','Reliable scoring putts','Putter · 3–6 ft putts',['green'],['Hit one 3-ft, one 4-ft and one 5-ft putt. Move after each ball.','Hole the putt.'],['Use three different 4–5 ft slopes around the hole.','Commit to the read and make at least two.'],['Three unique 5–6 ft pressure putts with full routine.','Make the putt on the first attempt.']),
A('SK04','SKILL','Speed Ladder','Adapt pace to distance','Putter · 10–40 ft space',['green'],['Choose 10, 20 and 30 ft targets. Roll one ball to each distance.','Finish inside a 3-ft depth zone.'],['Go short-long-medium and change line as well as distance.','Adapt speed immediately.'],['Use three random distances with no repeated putt.','Good first-attempt pace.']),
A('SK05','SKILL','Read & Commit','Make a read and trust it','Putter · varied 5–15 ft putts',['green'],['Read three different putts from behind the ball. Choose a start line before setup.','Decision is clear before setup.'],['Change length and slope. Once set, do not step out to re-read.','Roll on the committed read.'],['Three unique putts with full routine and no second guessing.','Read, commit, accept result.']),
A('SK06','SKILL','Playable Tee Ball','Keep the hole in play','Driver or tee club · define a fairway corridor',['range','bay'],['Choose two landmarks that create a generous fairway. Hit three tee balls.','Ball finishes in the playable corridor.'],['Narrow to a realistic fairway and change imagined hole each ball.','A shot you would happily play next.'],['Three different simulated holes with full routine and one ball each.','No penalty or recovery result.']),
A('SK07','SKILL','Wedge Distance','Control partial-wedge carry','Wedges · known targets',['range','bay'],['Choose three comfortable carry numbers. Hit one ball to each.','Carry finishes in the chosen distance window.'],['Randomize the three numbers and choose club or feel before each ball.','Correct carry on first attempt.'],['Three new scoring-yardage shots with full routine.','Commit to the number and execute it.']),
A('SK08','SKILL','Approach Window','Hit approaches into useful dispersion','Three irons · targets',['range','bay'],['Choose one target and a generous left-right window. Hit three balls with one club.','Finish in the window.'],['Use three clubs and three targets; define the safe window before each ball.','Playable approach with each club.'],['Three simulated approaches with different clubs and consequences.','Avoid the bad-side or penalty miss.']),
A('SK09','SKILL','Trajectory','Produce low, stock and higher windows','Mid-iron',['range','bay'],['Hit one lower, one stock and one slightly higher shot. Keep effort comfortable.','Flight visibly matches the call and stays playable.'],['Randomize low, stock and high and change target each ball.','Produce the called window on first attempt.'],['Choose trajectory for three imagined course situations.','Flight supports the shot decision.']),
A('SK10','SKILL','Curve Awareness','Plan around normal curvature','Mid-iron',['range','bay'],['Hit three stock shots and identify the normal curve after each. Do not try to change it.','You can describe the pattern.'],['Aim with room for the stock curve and change target each ball.','Curve finishes in a playable window.'],['Three simulated shots where you plan around your real pattern.','Manage curve rather than fight it.']),
A('SK11','SKILL','Club Selection','Choose club before execution','Several irons · known targets',['range','bay'],['Choose three known targets. Select the club before hitting and do not hit a test ball.','Club choice produces playable carry.'],['Use between-club targets and choose the comfortable solution.','Decision protects against an obvious short or long miss.'],['Three simulated approach decisions with full routine.','Choose first, then execute without indecision.']),
A('SK12','SKILL','Pressure Three','Commit when the ball matters','Any club · success window',['range','bay'],['Before each ball define a generous success window. Step away fully between shots.','Ball finishes in the called safe area.'],['Reduce the window slightly and change club each ball.','Routine stays the same as consequence rises.'],['Treat the final three as closing holes; one ball only.','Clear target and committed swing.']),
A('SK13','SKILL','Recovery Window','Choose safe recovery shots','Mid or short iron · landmarks',['range','bay'],['Choose a low, wide recovery window. Hit three controlled shots through it.','Ball exits through the safe window.'],['Change safe target and club each ball.','Advance safely without forcing a hero shot.'],['Three imagined trouble situations; choose the boring recovery first.','Avoid compounding the mistake.']),
A('SK14','SKILL','Basic Chip','Land and roll a simple chip predictably','Wedge or short iron · fringe',['short'],['Choose one landing spot and one hole. Hit three chips from the same simple lie.','First bounce near the spot; finish inside 6 ft.'],['Change hole, landing spot and lie each ball.','Choose enough landing and roll for each shot.'],['Three one-ball chip situations; no repeats.','First attempt gives a realistic par putt.']),
A('SK15','SKILL','Pitch Control','Control carry on higher short-game shots','Wedge · suitable targets',['short','range'],['Choose one landing or carry zone and hit three pitches.','Carry lands in the chosen zone.'],['Use short, medium and longer carry targets.','Match the called carry on first attempt.'],['Three different pitch situations with new targets.','Choose carry and create useful proximity.']),
A('SK16','SKILL','Bunker Exit','Prioritize safe bunker escape','Sand wedge · practice bunker',['short'],['Use a comfortable lie and generous green target. Hit three bunker shots.','Ball exits bunker and stays on green.'],['Change target and normal practice lie each ball.','Safe exit with useful distance.'],['Three one-ball bunker situations.','No wasted shot in the sand.']),
A('SK17','SKILL','Landing Spot','Choose where the short-game shot should land','Wedge or short iron · green',['short'],['Pick a visible landing spot before each of three chips. Keep the lie simple.','First bounce is near the chosen spot.'],['Change lie, hole and club option while keeping a clear landing plan.','Landing decision adapts to the situation.'],['Three one-ball scoring shots using landing-spot planning.','Plan creates a makeable next putt.']),
A('SK18','SKILL','Up & Down','Turn practice into scoring','Wedge + putter',['short'],['Choose three easy chip-and-putt situations. Play each ball until holed.','Complete in two shots.'],['Use three different normal lies and holes.','Choose the shot, then save par.'],['Three pressure up-and-down attempts; no repeated lie.','Score the first attempt and accept it.'])
];

export const TIP9_CONTEXTS={range:'Range',bay:'Hitting Bay',green:'Putting Green',short:'Short Game',noball:'No Ball'};
